### ISSUE TITLE
Add HTMX Monad?

### ISSUE THREAD

**Issue by rashadg1030** [MonadicSystems/lucid-htmx#2]
May need a Reader monad for storing the base URL for links generated by safeLink. They only display the endpoint without the base URL. May not be needed depending on HTMX behavior.

**Comment by bitc** [comment]
Is there anything special about HTMX that makes HTMX links different from regular HTML `<a href="...">` links?

If not, then such a Reader monad could be a more general hackage library for combining servant links with lucid

**Comment by rashadg1030** [comment]
@bitc I'm just reading this comment, sorry for the late reply! I need to turn notifications on! Thank you for the contribution by the way. Your PR has been merged.

Yeah so it turns out that using `safeLink` alone without a Reader monad or anything will work just fine. The safe variants such as `hxGetSafe_`, `hxPostSafe_`, etc. work perfect with just the `safeLink` function. I have some examples that I plan on porting to this repo. Perhaps in the docs.
