### ISSUE TITLE
Include hyperscript attribute?

### ISSUE THREAD

**Issue by tonyalaribe** [MonadicSystems/lucid-htmx#4]
It's common for htmx to be used with hyperscript. What is your opinion about having the hyperscript _ attribute also defined in this package?

**Comment by rashadg1030** [comment]
Yes, I think this is a good idea. I will be adding it in the next release for sure. I also have plans for a hyperscript QuasiQuoter

**Comment by rashadg1030** [comment]
So, the _hyperscript attribute `__` has been implemented in a seperate package called `lucid-hyperscript`. You use a QuasiQuoter like so:

```haskell
ex4 :: Monad m => HtmlT m ()
ex4 = input_
    [ type_ "text"
    , placeholder_ "Search Quotes..."
    , [__|
        on keyup
          if the event's key is 'Escape'
            set my value to ''
            trigger keyup
          else
            show <blockquote/> in #quotes when its textContent contains my value
      |]
    ]
```

This gives the `input_` _hyperscript functionality

**Comment by tonyalaribe** [comment]
Wow, this is wonderful. I will take a closer look in a bit, but it looks great already.
I think the namings for the quasiquoter makes sense. It’s not a lucid function, so I don’t think it needs to follow the lucid _ naming convention. 

I will take a closer look, but I think the most important nice to have will be Haskell value interpolation in the quasiquoters. Those are usually very important in practice
