### ISSUE TITLE
The repo contains `dist-newstyle`

### ISSUE THREAD

**Issue by rycee** [MonadicSystems/lucid-htmx#7]
It seems a `dist-newstyle` directory was accidentally added in the [latest commit](https://github.com/MonadicSystems/lucid-htmx/commit/aa975b8377ec7fafa060a54df5aec0e70ad85253). Probably best to remove it and add `/dist-newstyle` to `.gitignore` 🙂

**Comment by rashadg1030** [comment]
Thank you @rycee.
