### ISSUE TITLE
separate into two packages

### ISSUE THREAD

**Issue by henrylaxen** [MonadicSystems/lucid-htmx#8]
Just a suggestion:

Break this into two separate packages, say lucid-htmx and lucid-htmx-servant so that lucid-htmx does not depend on servant for those of us that do not use servant. (ex: snap users)
Best wishes,
Henry Laxen

**Comment by rashadg1030** [comment]
Yes, I agree! I will do that over this weekend. I have another issue to knock out as well. Also, updating so that everything aligns with htmx-1.8.0

**Comment by rashadg1030** [comment]
@henrylaxen Oh! You already did it and you added tests. Amazing. Thank you for your contribution. I will release these changes on Hackage as well. Thanks again :)

**Comment by rashadg1030** [comment]
@henrylaxen Do you think it's important to keep compatibility with `lucid`? I personally will start using `lucid2` for everything, but not sure about everybody else.
